const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cameras=['ARRI ALEXA 35','ARRI ALEXA Mini LF','Sony VENICE 2','RED V-RAPTOR XL','Blackmagic URSA Cine 12K','ARRICAM LT · Kodak Vision3','Panavision System 65'];
const lenses=['ARRI Signature Prime','Panavision T Series Anamorphic','Cooke Panchro/i Classic','Cooke S8/i','ZEISS Supreme Prime','Hawk V-Lite Anamorphic'];
const angles=[['front','Фронтально'],['three-right','¾ справа'],['profile-right','Профиль справа'],['three-left','¾ слева'],['profile-left','Профиль слева'],['rear','Со спины'],['top','Top shot 90°'],['bird','С птичьего полёта'],['low','Нижний ракурс']];
const shotSizes=['Extreme wide','Wide shot','Full shot','Medium wide','Medium shot','Medium close-up','Close-up','Extreme close-up'];
const defaults=[['A','front','Medium shot',50],['B','three-right','Medium close-up',65],['C','profile-left','Close-up',85],['D','top','Wide shot',35]];
const refs={};
function angleText(v){return {front:'front-facing at eye level','three-right':'three-quarter view from camera-right','profile-right':'clean 90-degree right profile','three-left':'three-quarter view from camera-left','profile-left':'clean 90-degree left profile',rear:'rear view while preserving eyeline direction','top':'strict 90-degree top shot, camera directly above the action center',bird:'high bird’s-eye view revealing the scene geography',low:'low-angle view with physically accurate verticals'}[v]}
function render(){
 $('#cameraGrid').innerHTML=defaults.map(([name,angle,size,focal])=>`<article class="camera-card" data-name="${name}"><div class="camera-head"><b>CAMERA ${name}</b><small>Отдельный still shot · одна сцена</small></div><div class="camera-body"><label class="still-reference"><input type="file" accept="image/*"><img alt="Reference Camera ${name}"><span>＋ Референс для Camera ${name}<br><small>${name==='A'?'главный эталон сцены':'можно использовать кадр A'}</small></span></label><div class="camera-fields"><label class="wide">Что происходит в этом кадре<textarea class="action" rows="2">${name==='A'?'Основной master shot сцены':name==='B'?'Ответный дополнительный ракурс того же действия':name==='C'?'Эмоциональный портретный ракурс того же момента':'Географический верхний ракурс той же сцены'}</textarea></label><label>Ракурс<select class="angle">${angles.map(([v,t])=>`<option value="${v}" ${v===angle?'selected':''}>${t}</option>`).join('')}</select></label><label>Крупность<select class="size">${shotSizes.map(v=>`<option ${v===size?'selected':''}>${v}</option>`).join('')}</select></label><label>Камера<select class="camera">${cameras.map(v=>`<option>${v}</option>`).join('')}</select></label><label>Кинооптика<select class="lens">${lenses.map(v=>`<option>${v}</option>`).join('')}</select></label><label>Фокусное<input class="focal" type="number" min="14" max="200" value="${focal}"></label><label>Диафрагма<select class="aperture"><option>T1.4</option><option>T2.0</option><option selected>T2.8</option><option>T4.0</option><option>T5.6</option></select></label></div></div><pre class="camera-prompt"></pre><div class="camera-actions">${name!=='A'?'<button class="ghost inherit-ref">Взять референс A</button>':''}<button class="copy-button copy-one">Скопировать Camera ${name}</button></div></article>`).join('');bind();update();
}
function consistency(){const p=[];if($('#lockCharacter').checked)p.push('the exact same character with unchanged face, age, body, hair, wardrobe, and accessories');if($('#lockLocation').checked)p.push('the same location with unchanged geography, architecture, materials, props, and object placement');if($('#lockLook').checked)p.push('the same moment, light direction and hardness, exposure, white balance, and cinematic color grade');return p.join('; ')}
function prompt(card){const name=card.dataset.name,ref=refs[name]?'Use the uploaded reference as the exact visual anchor. ':refs.A?'Use the CAMERA A master reference as the exact scene anchor. ':'';return `CAMERA ${name} · SEPARATE STILL SHOT\n${$('#masterScene').value.trim()}.\n${card.querySelector('.action').value.trim()}.\nAngle: ${angleText(card.querySelector('.angle').value)}. Shot size: ${card.querySelector('.size').value}.\nShot on ${card.querySelector('.camera').value}, ${card.querySelector('.lens').value}, ${card.querySelector('.focal').value}mm, ${card.querySelector('.aperture').value}.\n${ref}Photorealistic cinematic still, natural skin and materials, physically accurate perspective, smooth highlight roll-off, wide dynamic range.\nCONSISTENCY LOCK: ${consistency()}. This is a new camera position within the same physical space, not a new scene; reveal only previously unseen surfaces in a plausible way.`}
function update(){const cards=$$('.camera-card');cards.forEach(c=>c.querySelector('.camera-prompt').textContent=prompt(c));$('#allPrompts').innerHTML=cards.map(c=>`<pre>${prompt(c)}</pre>`).join('')}
function bind(){$$('.camera-card').forEach(card=>{card.querySelectorAll('textarea,select,input[type=number]').forEach(e=>e.oninput=update);const input=card.querySelector('input[type=file]');input.onchange=e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f),name=card.dataset.name;refs[name]={url,fileName:f.name};const img=card.querySelector('img'),span=card.querySelector('.still-reference span');img.src=url;img.style.display='block';span.style.display='none';update()};card.querySelector('.copy-one').onclick=()=>copy(prompt(card));const inherit=card.querySelector('.inherit-ref');if(inherit)inherit.onclick=()=>{if(!refs.A){toast('Сначала загрузите референс Camera A');return}refs[card.dataset.name]={...refs.A};const img=card.querySelector('img');img.src=refs.A.url;img.style.display='block';card.querySelector('.still-reference span').style.display='none';update();toast('Референс A подключён')}})}
['masterScene','lockCharacter','lockLocation','lockLook'].forEach(id=>$(`#${id}`).oninput=update);
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Промпт скопирован')}catch{toast('Скопируйте текст вручную')}}
$('#copyAll').onclick=()=>copy($$('.camera-card').map(c=>prompt(c)).join('\n\n====================\n\n'));
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
render();
