const $=s=>document.querySelector(s);
const modes={
 sketch:{n:'Sketch',d:'Чистый режиссёрский скетч: композиция и перспектива сохраняются.',f:[['detail','Детализация','range','70']],t:s=>`Transform ${s.src} into a clean cinematic composition sketch with balanced linework, readable structure and controlled grayscale shading. Use the source as a strict blueprint.`},
 composition:{n:'Composition',d:'Скетч фиксирует композицию, а референсы дают стиль, материалы и свет.',f:[['ref1','Референс 1','text','@img1'],['ref2','Референс 2','text','@img2'],['ref3','Референс 3','text','@img3']],t:s=>`Use ${s.src} as the strict composition blueprint. Use ${s.ref1||'no reference'}, ${s.ref2||'no reference'} and ${s.ref3||'no reference'} only for design, materials, lighting, color or style. If a reference conflicts with the blueprint, the blueprint wins.`},
 enhance:{n:'Enhance',d:'Контролируемая детализация без жёстких контуров и переделки кадра.',f:[['strength','Сила','range','55']],t:s=>`Enhance ${s.src} with ${s.strength>70?'strong':'controlled'} clarity, natural edge precision and improved local detail. Avoid halos, crunchy sharpness, waxy texture and an overprocessed AI look.`},
 anti:{n:'Anti‑CGI',d:'Убирает пластиковый AI/CGI-вид и возвращает физичные материалы.',f:[['strength','Сила де‑CGI','range','65']],t:s=>`De-CGI ${s.src}. Replace synthetic rendering with believable photographic material response, natural micro-contrast, subtle optical imperfections, realistic skin and fabric texture, physically plausible light falloff and restrained film grain.`},
 chroma:{n:'Chroma Key',d:'Заменяет green/blue screen, сохраняя края, волосы и логику света.',f:[['background','Новый фон','text','a cinematic dusk city street'],['color','Key color','select','green']],t:s=>`Replace the ${s.color} screen in ${s.src} with ${s.background}. Preserve fine hair, transparent edges, contact shadows, lens characteristics and original subject lighting. Avoid matte edges and color spill.`},
 clean:{n:'Clean BG',d:'Убирает отвлекающие объекты, оставляя сцену правдоподобной.',f:[['remove','Что убрать','text','distracting background clutter'],['background','После чистки','text','the same location, simplified and uncluttered']],t:s=>`Clean ${s.src}: remove only ${s.remove}. Reconstruct ${s.background} with matching perspective, materials, exposure, depth of field and light direction.`},
 marker:{n:'Marker Cleanup',d:'Удаляет tracking markers, tape и служебные линии.',f:[['remove','Что удалить','text','tracking markers, tape and guide lines']],t:s=>`Remove only ${s.remove} from ${s.src}. Reconstruct occluded surfaces seamlessly while preserving every other object, framing, texture, light and shadow.`},
 turn:{n:'Object Turn',d:'Создаёт новый угол объекта, сохраняя дизайн и материалы.',f:[['angle','Новый угол','select','three-quarter right'],['object','Объект','text','the main product or object']],t:s=>`Show ${s.object} from a ${s.angle} view, using ${s.src} as the strict identity reference. Preserve exact design, proportions, materials, color, scale and lighting logic. Keep it photorealistic and physically plausible.`},
 skin:{n:'Skin Realism',d:'Возвращает естественную живую кожу без фильтра и кукольного эффекта.',f:[['strength','Сила','range','60']],t:s=>`Improve skin realism in ${s.src} at a ${s.strength>70?'high':'natural'} level. Retain identity and expression. Restore believable pores, fine vellus hair, subtle asymmetry, natural under-eye detail and tonal variation. Avoid smoothing, waxiness and fake pores.`}
};let active='enhance';
function field([k,l,t,v]){if(t==='range')return `<div class="field full"><label>${l}<span class="value" id="${k}Value">${v}</span></label><input id="${k}" type="range" min="0" max="100" value="${v}"></div>`;if(t==='select'){let a=k==='color'?[['green','Green screen'],['blue','Blue screen']]:[['three-quarter right','¾ справа'],['three-quarter left','¾ слева'],['front','Фронтально'],['rear three-quarter','Задние ¾']];return `<div class="field"><label>${l}</label><select id="${k}">${a.map(x=>`<option value="${x[0]}" ${x[0]===v?'selected':''}>${x[1]}</option>`).join('')}</select></div>`}return `<div class="field"><label>${l}</label><input id="${k}" value="${v}"></div>`}
function get(){let s={src:$('#sourceRef').value.trim()||'@file01'};modes[active].f.forEach(([k])=>s[k]=$('#'+k)?.value||'');return s}
function update(){let s=get(),keep=[];if($('#keepComposition').checked)keep.push('Preserve exact composition, framing, camera angle, perspective, proportions and object placement.');if($('#keepLight').checked)keep.push('Preserve lighting direction, shadows, exposure and color palette.');if($('#keepIdentity').checked)keep.push('Preserve subject identity, anatomy, clothing, materials and important details.');if($('#noText').checked)keep.push('Do not add text, captions, logos, labels, symbols or watermarks.');$('#toolPrompt').textContent=`Image-to-image prompt.\n\nSource reference: ${s.src}\n\nMain task:\n${modes[active].t(s)}\n\nPreservation rules:\n${keep.join(' ')}\nDo not crop, zoom, rotate, stretch or reframe unless explicitly requested. Do not add random objects.\n\nOutput:\nA polished photorealistic result with coherent camera perspective, natural texture and cinematic image quality.`}
function render(){let m=modes[active];$('#modeTag').textContent=`IMAGE WORKFLOW · ${active.toUpperCase()}`;$('#modeName').textContent=m.n;$('#modeDescription').textContent=m.d;$('#fields').innerHTML=m.f.map(field).join('');$('#fields').querySelectorAll('input,select').forEach(e=>e.addEventListener('input',()=>{let o=$('#'+e.id+'Value');if(o)o.textContent=e.value;update()}));document.querySelectorAll('.tool-mode').forEach(e=>e.classList.toggle('active',e.dataset.mode===active));update()}
$('#toolNav').innerHTML=Object.entries(modes).map(([k,m],i)=>`<button class="tool-mode" data-mode="${k}"><i>${String(i+1).padStart(2,'0')}</i><span><b>${m.n}</b><small>${m.d}</small></span></button>`).join('');$('#toolNav').addEventListener('click',e=>{let b=e.target.closest('[data-mode]');if(b){active=b.dataset.mode;render()}});['sourceRef','keepComposition','keepLight','keepIdentity','noText'].forEach(i=>$('#'+i).addEventListener('input',update));$('#toolImage').addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;$('#sourceRef').value='@file01';$('#toolPreview').src=URL.createObjectURL(f);$('#toolPreview').style.display='block';$('#toolDrop').style.display='none';update()});$('#copyTool').addEventListener('click',async()=>{await navigator.clipboard.writeText($('#toolPrompt').textContent);$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1500)});render();
