const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let lang='en',variantIndex=0,nextId=6;
const plans=['Establishing wide','Medium shot','Close-up','Top shot','Hero final'];
const defaultScenes=['Общий план локации, герой входит в пространство','Средний план героя, действие развивается','Крупный план лица и эмоциональной реакции','Верхний план раскрывает географию события','Финальный hero shot, ясная завершённая композиция'];
const transitions={
  seamless:['Бесшовный match cut по форме, движению и направлению взгляда; первый пиксель нового кадра продолжает последний пиксель предыдущего.','Seamless match cut by shape, motion, and eyeline; the first pixels of the new shot continue the final pixels of the previous shot.'],
  liquid:['Жидкость полностью закрывает объектив и становится поверхностью следующего кадра; совпадают направление потока, цвет и скорость.','Liquid fully covers the lens and becomes the surface of the next shot; flow direction, color, and speed match.'],
  storm:['Вспышка молнии на один кадр пересвечивает изображение; громовая тень раскрывается уже в следующем плане той же сцены.','A one-frame lightning flash blows out the image; the thunder shadow resolves into the next angle of the same scene.'],
  rain:['Капли дождя собираются на объективе, одна крупная капля заполняет кадр и её блик превращается в следующий план.','Rain gathers on the lens; one large droplet fills the frame and its highlight transforms into the next shot.'],
  wall:['Камера быстро проходит вплотную за стеной или колонной; тёмная окклюзия скрывает склейку и открывает новый ракурс.','Camera passes tightly behind a wall or column; dark occlusion hides the cut and reveals the new angle.'],
  whip:['Резкий whip-pan создаёт направленный motion blur; новый кадр продолжает ту же скорость и направление, затем мягко стабилизируется.','A sharp whip-pan creates directional motion blur; the new shot continues the same speed and direction, then settles smoothly.']
};
const transitionNames={seamless:'Бесшовный match cut',liquid:'Через жидкость',storm:'Гроза / молния',rain:'Дождь по объективу',wall:'Через стену',whip:'Быстрое движение камеры'};
const makeShot=(scene,i)=>({id:i+1,duration:2,plan:plans[i]||'Medium shot',scene,movement:i===0?'Slow push in':'',angle:'на уровне глаз',optics:'50 мм, кинематографичная глубина резкости',light:'согласован со сценой',transition:'seamless',note:'',refName:'',refEnabled:false,refTag:`@file${String(i+1).padStart(2,'0')}`,refRole:i===0?'Первый кадр':'Visual anchor'});
let shots=defaultScenes.map(makeShot);

function render(){
  $('#shots').innerHTML=shots.map((s,i)=>`<article class="shot-card" data-id="${s.id}"><div class="shot-head"><span class="shot-number">SHOT ${String(i+1).padStart(2,'0')}</span><b>${s.plan}</b><label><input class="duration" type="number" min="0.5" max="15" step="0.5" value="${s.duration}"> сек</label><button class="remove-shot" title="Удалить">×</button></div><div class="shot-body"><div class="reference-panel"><label class="reference-drop"><input class="ref-input" type="file" accept="image/*"><img alt="Референс"><span>${s.refName||'＋ Референс'}</span></label><div class="ref-link"><label class="ref-check"><input class="ref-enabled" type="checkbox" ${s.refEnabled?'checked':''}> Указать ссылку</label><input class="ref-tag" value="${s.refTag}" placeholder="@file01"><select class="ref-role"><option ${s.refRole==='Первый кадр'?'selected':''}>Первый кадр</option><option ${s.refRole==='Последний кадр'?'selected':''}>Последний кадр</option><option ${s.refRole==='Visual anchor'?'selected':''}>Visual anchor</option><option ${s.refRole==='Персонаж'?'selected':''}>Персонаж</option><option ${s.refRole==='Локация'?'selected':''}>Локация</option></select></div></div><div class="shot-fields"><label class="wide">Содержание и действие кадра<textarea class="scene" rows="3">${s.scene}</textarea></label><label>Тип плана<select class="plan">${plans.map(p=>`<option ${p===s.plan?'selected':''}>${p}</option>`).join('')}<option>Macro detail</option><option>Over-the-shoulder</option><option>Bird’s-eye view</option><option>Low angle</option></select></label><label>Ракурс<input class="angle" value="${s.angle}" placeholder="¾ справа, top shot…"></label><label>Оптика<input class="optics" value="${s.optics}" placeholder="50 мм, T2.8, anamorphic"></label><label>Движение камеры<input class="movement" value="${s.movement}" placeholder="Например: slow arc right"></label><label>Свет кадра<input class="shot-light" value="${s.light}" placeholder="Мягкий контровой свет"></label></div></div>${i<shots.length-1?`<div class="transition-row"><span>ПЕРЕХОД → SHOT ${String(i+2).padStart(2,'0')}</span><select class="transition">${Object.entries(transitionNames).map(([k,v])=>`<option value="${k}" ${k===s.transition?'selected':''}>${v}</option>`).join('')}</select><input class="transition-note" value="${s.note}" placeholder="Уточнение перехода…"></div>`:''}</article>`).join('');
  bindCards();update();
}
function bindCards(){
  $$('.shot-card').forEach((card,i)=>{const s=shots[i];card.querySelector('.duration').oninput=e=>{s.duration=+e.target.value;update()};card.querySelector('.scene').oninput=e=>{s.scene=e.target.value;update()};card.querySelector('.plan').onchange=e=>{s.plan=e.target.value;card.querySelector('.shot-head b').textContent=s.plan;update()};card.querySelector('.angle').oninput=e=>{s.angle=e.target.value;update()};card.querySelector('.optics').oninput=e=>{s.optics=e.target.value;update()};card.querySelector('.shot-light').oninput=e=>{s.light=e.target.value;update()};card.querySelector('.movement').oninput=e=>{s.movement=e.target.value;update()};card.querySelector('.ref-enabled').oninput=e=>{s.refEnabled=e.target.checked;update()};card.querySelector('.ref-tag').oninput=e=>{s.refTag=e.target.value;update()};card.querySelector('.ref-role').onchange=e=>{s.refRole=e.target.value;update()};card.querySelector('.remove-shot').onclick=()=>{if(shots.length>1){shots.splice(i,1);render()}};const tr=card.querySelector('.transition');if(tr)tr.onchange=e=>{s.transition=e.target.value;if(s.transition!=='seamless')$('#seamlessDefault').checked=false;update()};const note=card.querySelector('.transition-note');if(note)note.oninput=e=>{s.note=e.target.value;update()};const file=card.querySelector('.ref-input');file.onchange=e=>{const f=e.target.files[0];if(!f)return;s.refName=f.name;s.refEnabled=true;const img=card.querySelector('.reference-drop img'),span=card.querySelector('.reference-drop span'),check=card.querySelector('.ref-enabled');img.src=URL.createObjectURL(f);img.style.display='block';span.style.display='none';check.checked=true;update()};});
}
function update(){
  const total=shots.reduce((a,s)=>a+s.duration,0),target=+$('#totalDuration').value;
  $('#durationStatus').textContent=`${shots.length} планов · ${total.toFixed(1)} сек${Math.abs(total-target)>.01?` / цель ${target} сек`:''}`;
  $('#timeline').innerHTML=shots.map((s,i)=>`<div class="time-segment" style="flex:${s.duration}">${i+1} · ${s.duration}s</div>`).join('');
  const continuityRu=$('#lockContinuity').checked?'Зафиксировать одного персонажа, костюм, реквизит, географию локации, время суток, направление света, цвет и экспозицию во всех планах. Соблюдать ось 180° и непрерывность действия.':'';
  const continuityEn=$('#lockContinuity').checked?'Lock the same character, wardrobe, props, location geography, time of day, light direction, color, and exposure across every shot. Preserve the 180-degree line and action continuity.':'';
  const copyMove=$('#inheritMovement').checked;
  const brief=$('#sceneBrief').value.trim(),style=$('#visualStyle').value.trim(),lighting=$('#lighting').value.trim(),globalOptics=$('#globalOptics').value.trim(),negative=$('#globalNegative').value.trim();
  const header=lang==='ru'?`МНОГОПЛАНОВАЯ СЦЕНА · ${$('#videoModel').value} · ${target} секунд · ${$('#aspectRatio').value}\nКОНЦЕПЦИЯ: ${brief}.\nВИЗУАЛЬНЫЙ СТИЛЬ: ${style}.\nСВЕТ: ${lighting}.\nОПТИКА: ${globalOptics}.\n${continuityRu}\nNEGATIVE: ${negative}.`:`MULTI-SHOT SCENE · ${$('#videoModel').value} · ${target} seconds · ${$('#aspectRatio').value}\nCONCEPT: ${brief}.\nVISUAL STYLE: ${style}.\nLIGHTING: ${lighting}.\nOPTICS: ${globalOptics}.\n${continuityEn}\nNEGATIVE: ${negative}.`;
  const body=shots.map((s,i)=>{const inherited=copyMove&&!s.movement?[...shots.slice(0,i)].reverse().find(x=>x.movement)?.movement:s.movement;const ref=s.refEnabled&&s.refTag?(lang==='ru'?`РЕФЕРЕНС ${s.refTag}: роль — ${s.refRole}; использовать как точный visual anchor${s.refName?` (файл «${s.refName}»)`:''}.`:`REFERENCE ${s.refTag}: role — ${s.refRole}; use as an exact visual anchor${s.refName?` (file “${s.refName}”)`:''}.`):'';const shot=lang==='ru'?`SHOT ${i+1} · ${s.duration} сек · ${s.plan}\n${s.scene}.\nРакурс: ${s.angle}. Оптика: ${s.optics}. Свет: ${s.light}.\nКамера: ${inherited||'статичная, композиционно мотивированная'}. ${ref}`:`SHOT ${i+1} · ${s.duration} sec · ${s.plan}\n${s.scene}.\nAngle: ${s.angle}. Optics: ${s.optics}. Light: ${s.light}.\nCamera: ${inherited||'static, compositionally motivated'}. ${ref}`;if(i===shots.length-1)return shot;const t=transitions[s.transition][lang==='ru'?0:1];return `${shot}\n${lang==='ru'?'ПЕРЕХОД':'TRANSITION'} ${i+1}→${i+2}: ${t}${s.note?' '+s.note:''}`}).join('\n\n');
  $('#sequencePrompt').textContent=`${header}\n\n${body}`;
}
$('#addShot').onclick=()=>{const shot=makeShot('Новый план той же сцены',shots.length);shot.id=nextId++;shots.push(shot);render()};
$('#variantBtn').onclick=()=>{variantIndex++;shots.slice(0,-1).forEach((s,i)=>s.transition=Object.keys(transitions)[(i+variantIndex)%6]);render();toast('Вариант переходов обновлён')};
$('#resetSequence').onclick=()=>{shots=defaultScenes.map(makeShot);$('#seamlessDefault').checked=true;render()};
$('#seamlessDefault').oninput=e=>{if(e.target.checked){shots.slice(0,-1).forEach(s=>s.transition='seamless');render()}else update()};
['videoModel','totalDuration','aspectRatio','inheritMovement','lockContinuity','sceneBrief','visualStyle','lighting','globalOptics','globalNegative'].forEach(id=>$(`#${id}`).oninput=update);
$$('.language-toggle button').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;$$('.language-toggle button').forEach(x=>x.classList.toggle('active',x===b));update()});
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
$('#copySequence').onclick=async()=>{try{await navigator.clipboard.writeText($('#sequencePrompt').textContent);toast('Промпт скопирован')}catch{toast('Выделите текст вручную')}};
render();
